# name: Periodic Link Checker 

# on:
#     schedule:
#       - cron: '0 0 * * 0'  # Run every Sunday midnight (UTC time)
# jobs:
#   link_check:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./linkchecker/
        
#     strategy:
#       matrix:
#         python-version: [3.11]

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r ./requirements.txt

#         # Add this step to set up Docker Buildx
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
        
#       - name: Run app code
#         run: python ./linkchecker.py

#       - name: Run fast api
#         run: |
#           python -m uvicorn api:app --reload --host 0.0.0.0 --port 8000
    