# name: Periodic Link Checker

# on:
#   schedule:
#     - cron: '0 0 * * 0' # Run every Sunday at midnight (UTC time)

# jobs:
#   link_check:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./linkchecker/
#     strategy:
#       matrix:
#         python-version: [3.11]

#     steps:
#     - uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: ${{ matrix.python-version }}

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run link checker script
#       env:
#         POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#         POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
#         POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
#         POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
#       run: python linkchecker.py

#     - name: Run FastAPI server
#       env:
#         POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#         POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
#         POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
#         POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
#       run: |
#         nohup python -m uvicorn api:app --host 0.0.0.0 --port 8000 &
